#!/usr/bin/env bash
# Regenerate the CENDL-3.2 MAT table fragment.
#
# Run when CENDL releases a new version (just edit the URL) or when re-validating.
# Output is a Rust source fragment to paste into `crates/endf-mat/src/mat.rs`
# under the existing ENDF_MAT_TABLE / TENDL_2023_MAT_TABLE definitions.
#
# Usage:
#   bash crates/endf-mat/scripts/regenerate_cendl_table.sh > /tmp/cendl_fragment.rs
#
# The script:
#   1. Fetches the IAEA directory listing for CENDL-3.2 neutrons sublibrary.
#   2. Parses filenames matching `n_{z:03}-{Sym}-{a}_{mat:04}.zip` into (Z, A, MAT)
#      triples (CENDL-3.2 has no metastables in the neutron sublibrary).
#   3. Sanity-checks each triple (Z ∈ [0,118], A ≥ Z, MAT 4-digit) and fails loud
#      on any anomaly.
#   4. Sorts by (Z, A) for binary-search compatibility.
#   5. Emits a Rust array literal source fragment.
#
# Network caveat: IAEA's www-nds.iaea.org is fronted by Cloudflare's managed
# challenge that 403s commercial-VPN exit IPs. **Run off-VPN.**

set -euo pipefail

URL="https://www-nds.iaea.org/public/download-endf/CENDL-3.2/n/"

listing=$(curl -fsSL --max-time 60 "$URL") || {
    echo "ERROR: failed to fetch $URL (curl returned non-2xx or transport error)" >&2
    echo "       If HTTP 403, disconnect from VPN — IAEA's Cloudflare gate filters" >&2
    echo "       commercial-VPN exit IPs by reputation." >&2
    exit 1
}
if [ -z "$listing" ]; then
    echo "ERROR: empty listing from $URL" >&2
    exit 1
fi

# Extract triples (Z, A, MAT) from filenames like n_056-Ba-138_5649.zip
# AWK splits on _ and . to isolate the numeric fields. Z is leading-zero
# padded (3 digits), A is unpadded, MAT is leading-zero padded (4 digits).
# Skip:
#   - A=0 (natural-element evaluations like n_017-Cl-0_*.zip — CENDL-3.2 has 11
#     of these for Cl, K, Ca, V, Cu, Ge, Ag, Cd, Sn, Hg, Tl) — `Isotope::new`
#     requires A > 0, and ENDF_MAT_TABLE / TENDL_2023_MAT_TABLE follow the same
#     convention.
triples=$(printf '%s' "$listing" \
    | grep -oE 'n_[0-9]+-[A-Za-z]+-[0-9]+_[0-9]+\.zip' \
    | awk -F'[_.-]' '$4 > 0 { printf "%d %d %d\n", $2, $4, $5 }' \
    | sort -k1,1n -k2,2n \
    | uniq)

count=$(printf '%s\n' "$triples" | wc -l | tr -d ' ')

# Sanity validation. CENDL-3.2 has ~270 isotopes (vs TENDL's ~2300, ENDF/B-VIII.0's
# 535). Bounds chosen to fail loud on a truncated/expanded listing.
echo "$triples" | awk -v expect_min=200 -v expect_max=350 '
    {
        z=$1; a=$2; mat=$3
        if (z < 0 || z > 118)             { printf "ERROR: Z=%d out of range\n", z > "/dev/stderr"; exit 1 }
        if (a < z)                         { printf "ERROR: A=%d < Z=%d\n", a, z > "/dev/stderr"; exit 1 }
        if (mat < 1 || mat > 9999)         { printf "ERROR: MAT=%d out of 4-digit range\n", mat > "/dev/stderr"; exit 1 }
        n++
    }
    END {
        if (n < expect_min || n > expect_max) {
            printf "ERROR: %d entries — outside expected [%d, %d] for CENDL-3.2\n", n, expect_min, expect_max > "/dev/stderr"
            exit 1
        }
        printf "validation OK: %d entries\n", n > "/dev/stderr"
    }
'

cat <<EOF
// Auto-generated by crates/endf-mat/scripts/regenerate_cendl_table.sh
// Source: https://www-nds.iaea.org/public/download-endf/CENDL-3.2/n/
// $count entries (CENDL-3.2 neutron sublibrary, including free neutron).
// DO NOT EDIT BY HAND — re-run the regenerator if the upstream listing changes.
#[rustfmt::skip]
static CENDL_3_2_MAT_TABLE: &[(u32, u32, u32)] = &[
EOF

printf '%s\n' "$triples" | awk '{ printf "    (%d, %d, %d),\n", $1, $2, $3 }'

echo "];"
